version: '3.7'

services:
  pgsql:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: conT0m@te
      POSTGRES_USER: monhigas
      POSTGRES_DB: redflagdb
    ports:
      - "5432:5432"
    volumes:
      - demo_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "pgsql"
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_NAME: redflagdb
volumes:
  demo_data: {}
